### ISSUE TITLE
基于chromium 的XSS 检测工具，恳请收录

### ISSUE THREAD

**Issue by v8blink** [guchangan1/All-Defense-Tool#1]
Cyclops 是一款具有 XSS 检测功能的浏览器。Cyclops 以 Chromium 源码为基础，添加了动态污染追踪（Taint Tracking）技术，可以详细监测攻击者可控的输入源（source）与威胁发生点（sink）之间的数据流动，为人工验证提供详实可靠的依据。
下载地址：https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking

**Comment by guchangan1** [comment]
感谢您的提交 已收录至插件栏 将在下次更新时发布
