### ISSUE TITLE
谷歌插件版本- superSearchPlus是聚合型信息收集插件

### ISSUE THREAD

**Issue by ThestaRY7** [guchangan1/All-Defense-Tool#10]
https://github.com/dark-kingA/superSearchPlus

 谷歌插件版本- superSearchPlus是聚合型信息收集插件，支持综合查询，资产测绘查询，信息收集 敏感信息提取 js资源扫描 目录扫描 vue组件扫描 整合了目前常见的资产测绘平台 同时支持数据导出

**Comment by guchangan1** [comment]
感谢提交，已收录，将在下次更新时展示。
